json.id p.id
json.first_name p.first_name
json.last_name p.last_name
json.birth_date p.birth_date
json.death_date p.death_date
json.gender p.gender
json.email p.email
json.uuid p.uuid
json.deleted_at p.deleted_at
json.created_at p.created_at
json.created_at p.created_at